baseURL = "https://dopaminegirl19.github.io/bookclub"
languageCode = "en-us"
title = "Faculty book club"
theme="archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false

[[menu.main]]
name = "read"
url = "/"
weight = 1

[[menu.main]]
name = "suggest"
url = "/suggest"
weight = 2

[[menu.main]]
name = "vote"
url = "/vote"
weight = 3
